[build]# ── Netlify Configuration ──

  publish = "dist"[build]

  command = "npm run build"  command = "npm run build"    # Run Vite's production build

  publish = "dist"             # Directory to deploy

[[redirects]]

  from = "/*"# ── Redirects for SPA Routing ──

  to = "/index.html"[[redirects]]

  status = 200  from = "/*"

  to = "/index.html"

[build.environment]  status = 200

  NODE_VERSION = "18"
# ── Caching (optional but useful) ──
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ── Development (optional, for `netlify dev`) ──
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  framework = "vite"

# ── Environment (optional example) ──
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
